name: Cubical Productions
favicon: null
layout_spectrum: 0.8828162192367017
typography_spectrum: 0.8191264776978642
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.06820447463542223
  lightness: 0.29219804564490914
  saturation: 0.21697496250271797
  rhythmicContrast: 0.6778373261913657
purpose: []
