name: Cubical Productions
favicon: null
layout_spectrum: 0.50326
typography_spectrum: 0.36193
title: The official portfolio site of Cubical Productions
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#979797'
    - '#505050'
    - '#57b9ba'
    - '#1b8f8f'
  brandStrength: 0.125
  lightness: 0.4375
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
